version: "3.9"
services:
  cloud-lb:
    build: .
    container_name: cloud_lb_app
    volumes:
    #  - ./database.db:/app/database.db
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    stdin_open: true
    tty: true

